### PR TITLE
Add basic auth fields in config method

### PR DESCRIPTION
**Pull request by uLan08**
Hey, got some code in. Let me know if there's something I missed. Also do you think we could a new validator that validates `user:hash,user:hash` format?

### CODE REVIEW

**Comment by yamalight** [comment]
This is great, thank you! 👍

**Comment by yamalight** [comment]
W.r.t. format and validation - we can discuss this after initial basic implementation 😄 
Ideally I'd want `exoframe config` to generate `user:hash` from user's username and password input 🤔 
But that can be done later on.
Thank you for this PR once again! 👍

**Comment by uLan08** [comment]
I forgot to add to the Docs 😅

**Comment by yamalight** [comment]
I totally do that all the time too 😅 
Feel free to send them over as another PR 👍

**Comment by uLan08** [comment]
Ha, alright. Thanks!

**Pull request merged**
