### PR TITLE
Add auto encrypt of username password pairs for basic auth

### LINKED ISSUE #168: Add frontend auth support
Traefik 1.7 introduced auth support for front-ends.
It can be achieved by using the following label:
```
# Sets basic authentication for that frontend in CSV format: User:Hash,User:Hash [2]
traefik.frontend.auth.basic=EXPR

[2] traefik.frontend.auth.basic=EXPR: To create user:password pair, it's possible to use this command echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g. The result will be user:$$apr1$$9Cv/OMGj$$ZomWQzuQbL.3TRCS81A1g/, note additional symbol $ makes escaping.
```
We should add support for this in config file.

### PR DESCRIPTION
**Pull request by uLan08**
Introduced two new packages:
  - [inquirer-recursive](https://github.com/nathanloisel/inquirer-recursive)
  - [apache-md5](https://github.com/http-auth/apache-md5)

Also updated `yarn.lock` file with integrity hashes using `yarn 1.10.1`

Should now close #168

### CODE REVIEW

**Comment by yamalight** [comment]
This is great, thank you! ❤️ 
I'll test and merge it on Monday 👍

**Comment by uLan08** [comment]
All good! I just wasn't able to find a way to mock the recursive prompts in the test. Let me know if you can think of something, I can just add it in.

**Comment by yamalight** [comment]
@uLan08 looks great!
mocking recursive prompts should be relative easy since it's just successive calls to inquirer.
so it'd be something like this for my code above:
```js
test('should run with loop', async () => {
  // stup inquirer answers
  sinon
    .stub(inquirer, 'prompt')
    // answer main questions
    .onFirstCall()
    .callsFake(() => Promise.resolve({name: 'test', basicAuth: true}))
    // answer first recursive question and say we want to continue
    .onSecondCall()
    .callsFake(() => Promise.resolve({username: 'user', password: 'pass', askAgain: true}))
    // answer second recursive question and say we want to quit
    .onThirdCall()
    .callsFake(() => Promise.resolve({username: 'user2', password: 'pass2', askAgain: false}));

// ...
});
```

**Comment by uLan08** [comment]
That is easy! I guess my unfamiliarity with sinon really showed.

**Comment by yamalight** [comment]
@uLan08 this is amazing, thank you! 👍

**Pull request merged**
