### PR TITLE
Fail early if the configuration is invalid JSON 

### PR DESCRIPTION
**Pull request by schorsch3000**
This addresses #38 
I try to parse the configuration as early as possible to stop the deployment on a broken configuration.

I'm not sure about the error-reporting-method.
Let me know if we should report in a different way.

### CODE REVIEW

**Comment by yamalight** [comment]
Looks good, but a few little moments:

1. Please re-format the code using prettier and make sure it passes eslint check (I probably should add that to tests)
2. Please add the following message after spinner error: "Please, check your config and try again."
3. (optional) Would be nice to have a unit test that covers this case (I can add this myself after merge too)

**Comment by schorsch3000** [comment]
1 and 2 are done.
i'm afraid am not fluent in tap, if it's okay to you i would like to leave that part up to you.

**Comment by yamalight** [comment]
I'll handle the tests, no worries. One more thing - can you please make a PR into `develop`, not `master`?

**Comment by yamalight** [comment]
Merged. Thanks for the contribution! :)

**Comment by schorsch3000** [comment]
Nice.
No problem.
I try to elaborate exoframe at work for these "can we just deploy $software to test things out for a few days" kind of tasks.

**Comment by yamalight** [comment]
Awesome! Do let me know if you have any use cases that are not (yet) fit for exoframe due to lack of features - I'm happy to extend it :)

**Pull request merged**
