### PR TITLE
Extra information about docker-compose

### PR DESCRIPTION
**Pull request by Aeolun**
I’d basically never worked with traefik before, so the labels you could add were complete and utter magic to me. I felt it might be helpful to have a more explicit reference to the location you will find them.

### CODE REVIEW

**Comment by yamalight** [comment]
@Aeolun This is great, thank you! It basically addresses https://github.com/exoframejs/exoframe/issues/171.
One small request - could you please add that text to [Advanced.md](https://github.com/exoframejs/exoframe/blob/master/docs/Advanced.md) - don't think that creating another file just for a paragraph is worth it 🤔

**Comment by Aeolun** [comment]
@yamalight Sure, will update that.

**Comment by Aeolun** [comment]
@yamalight Sorry, that took a bit longer than expected, but it should be updated ;)

**Comment by yamalight** [comment]
@Aeolun looks great, thank you!

**Pull request merged**
